spring.application.name=ticket-queue

spring.config.import=optional:file:.env[.properties]
spring.profiles.active=${ACTIVE}

server.tomcat.threads.max=300
server.tomcat.threads.min-spare=30

# ===============================
# Virtual Thread
# ===============================
#spring.threads.virtual.enabled=true