spring.application.name=ticket-queue

server.tomcat.threads.max=300
server.tomcat.threads.min-spare=30

# ===============================
# Virtual Thread
# ===============================
#spring.threads.virtual.enabled=true


# jwt
spring.jwt.secret=Fr9Sod2TnNJtQBL1Y8HS3MJdYzxsaNc87oJYdANRcms=
# unit: min
# 1000 * 60 * 5 = 5min
#spring.jwt.accessExpiration=300000
# 1000 * 60 * 5 = 60min
#spring.jwt.refreshExpiration=3600000

ticket.booking.token.activeExpiration=300000
ticket.booking.token.waitingExpiration=3600000


# min
active.user.ttl=5

# booking service
#ticket.booking.capacity=100
ticket.booking.capacity=1